<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByDate($day, $month, $year, $order = "DESC") {
        $date = \DateTime::createFromFormat('d/m/Y', "$day/$month/$year");
        $qb = $this->getEntityManager()->createQueryBuilder();
        return $qb->select("article")
            ->from('AppBundle:Article', 'article')
            ->where("article.createdAt = :date")
            ->setParameter('date', $date)
            ->getQuery()
            ->getResult();
    }

}
