# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
     app.security.role_change_listener:
            class: AppBundle\RoleListener
            tags:
                - { name: kernel.event_subscriber }
            arguments:
                - '@doctrine.orm.default_entity_manager'
                - '@security.token_storage'

     app.twig_extensions:
            class: Twig_Extensions_Extension_Intl
            public: false
            tags:
                - { name: twig.extension }
     app.twig_extensions_text:
            class: Twig_Extensions_Extension_Text
            public: false
            tags:
                - { name: twig.extension }
     app.utils:
            class: AppBundle\Utils
            arguments: ['@swiftmailer.mailer', '@doctrine.orm.entity_manager', '@service_container']

     security.authentication.success_handler:
            class: AppBundle\Handler\AuthenticationSuccessHandler
            arguments: ['@security.http_utils', '@service_container', {}]
            tags:
                - { name: 'monolog.logger', channel: 'security'}

     logout_success_handler:
        class: AppBundle\Handler\LogoutSuccessHandler
        arguments: ['@security.http_utils', '@service_container']